# Generated by Django 3.2 on 2021-04-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20210429_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='user',
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expenses',
            name='list_n',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='user.list'),
        ),
    ]
