# Generated by Django 3.2 on 2021-04-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_expenses_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='user',
        ),
    ]
