# Generated by Django 3.2 on 2021-05-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
