# Generated by Django 3.2 on 2021-05-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_wishlist_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='days',
        ),
    ]
